language: go
sudo: false
go:
 - 1.x
 - tip

env:
 - GO111MODULE=on

matrix:
 allow_failures:
  - go: tip

before_install:
  - go get github.com/fzipp/gocyclo
  - go get honnef.co/go/tools/cmd/megacheck

script:
  make test