[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
    name = "pack.ag/amqp"
    version = ">=0.7, <0.9"

[[constraint]]
    name = "go.opencensus.io"
    version = "0.15"

[[constraint]]
	name = "github.com/Azure/go-autorest"
	version = "11.0.0"
